bilardex_api/config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :pool_tables
  resources :reservations
  resources :users
  resources :roles

  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/logout',  to: 'sessions#destroy'

  #get    '/reserve'  to: 'reservation_write#new'
  #get    '/reserve'  to: 'reservations#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

bilardex_api/app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :user, :join_table => :roles_users
end

bilardex_api/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to role_url(@role), notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to role_url(@role), notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:role_name, :user_read, :user_write, :reservation_read, :reservation_write, :pool_table_read, :pool_table_write, :payment_read, :payment_write, :api_permissions_write, :api_permissions_read)
    end
end

bilardex_api/app/helpers/roles_helper.rb
module RolesHelper
end

bilardex_api/app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :role_name, style: "display: block" %>
    <%= form.text_field :role_name %>
  </div>

  <div>
    <%= form.label :user_read, style: "display: block" %>
    <%= form.check_box :user_read %>
  </div>

  <div>
    <%= form.label :user_write, style: "display: block" %>
    <%= form.check_box :user_write %>
  </div>

  <div>
    <%= form.label :reservation_read, style: "display: block" %>
    <%= form.check_box :reservation_read %>
  </div>

  <div>
    <%= form.label :reservation_write, style: "display: block" %>
    <%= form.check_box :reservation_write %>
  </div>

  <div>
    <%= form.label :pool_table_read, style: "display: block" %>
    <%= form.check_box :pool_table_read %>
  </div>

  <div>
    <%= form.label :pool_table_write, style: "display: block" %>
    <%= form.check_box :pool_table_write %>
  </div>

  <div>
    <%= form.label :payment_read, style: "display: block" %>
    <%= form.check_box :payment_read %>
  </div>

  <div>
    <%= form.label :payment_write, style: "display: block" %>
    <%= form.check_box :payment_write %>
  </div>

  <div>
    <%= form.label :api_permissions_write, style: "display: block" %>
    <%= form.check_box :api_permissions_write %>
  </div>

  <div>
    <%= form.label :api_permissions_read, style: "display: block" %>
    <%= form.check_box :api_permissions_read %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

bilardex_api/app/views/roles/_role.html.erb
<div id="<%= dom_id role %>">
  <p>
    <strong>Role name:</strong>
    <%= role.role_name %>
  </p>

  <p>
    <strong>User read:</strong>
    <%= role.user_read %>
  </p>

  <p>
    <strong>User write:</strong>
    <%= role.user_write %>
  </p>

  <p>
    <strong>Reservation read:</strong>
    <%= role.reservation_read %>
  </p>

  <p>
    <strong>Reservation write:</strong>
    <%= role.reservation_write %>
  </p>

  <p>
    <strong>Pool table read:</strong>
    <%= role.pool_table_read %>
  </p>

  <p>
    <strong>Pool table write:</strong>
    <%= role.pool_table_write %>
  </p>

  <p>
    <strong>Payment read:</strong>
    <%= role.payment_read %>
  </p>

  <p>
    <strong>Payment write:</strong>
    <%= role.payment_write %>
  </p>

  <p>
    <strong>Api permissions write:</strong>
    <%= role.api_permissions_write %>
  </p>

  <p>
    <strong>Api permissions read:</strong>
    <%= role.api_permissions_read %>
  </p>

</div>

bilardex_api/app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Show this role", @role %> |
  <%= link_to "Back to roles", roles_path %>
</div>

bilardex_api/app/views/roles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Roles</h1>

<div id="roles">
  <% @roles.each do |role| %>
    <%= render role %>
    <p>
      <%= link_to "Show this role", role %>
    </p>
  <% end %>
</div>

<%= link_to "New role", new_role_path %>

bilardex_api/app/views/roles/new.html.erb
<h1>New role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Back to roles", roles_path %>
</div>

bilardex_api/app/views/roles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @role %>

<div>
  <%= link_to "Edit this role", edit_role_path(@role) %> |
  <%= link_to "Back to roles", roles_path %>

  <%= button_to "Destroy this role", @role, method: :delete %>
</div>