bilardex_api/config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :pool_tables
  resources :reservations
  resources :users
  resources :roles

  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/logout',  to: 'sessions#destroy'

  #get    '/reserve'  to: 'reservation_write#new'
  #get    '/reserve'  to: 'reservations#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

bilardex_api/app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :pool_table
  belongs_to :payment
end

bilardex_api/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:pool_table_id, :user_id, :start_time, :end_time, :payment_id)
    end
end

bilardex_api/app/helpers/reservations_helper.rb
module ReservationsHelper
end

bilardex_api/app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pool_table_id, style: "display: block" %>
    <%= form.number_field :pool_table_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <%= form.label :payment_id, style: "display: block" %>
    <%= form.number_field :payment_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

bilardex_api/app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
  <p>
    <strong>Pool table:</strong>
    <%= reservation.pool_table_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= reservation.user_id %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= reservation.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= reservation.end_time %>
  </p>

  <p>
    <strong>Payment:</strong>
    <%= reservation.payment_id %>
  </p>

</div>

bilardex_api/app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

bilardex_api/app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reservations</h1>

<div id="reservations">
  <% @reservations.each do |reservation| %>
    <%= render reservation %>
    <p>
      <%= link_to "Show this reservation", reservation %>
    </p>
  <% end %>
</div>

<%= link_to "New reservation", new_reservation_path %>

bilardex_api/app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Back to reservations", reservations_path %>
</div>

bilardex_api/app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>
  <%= link_to "Edit this reservation", edit_reservation_path(@reservation) %> |
  <%= link_to "Back to reservations", reservations_path %>

  <%= button_to "Destroy this reservation", @reservation, method: :delete %>
</div>