bilardex_api/config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :pool_tables
  resources :reservations
  resources :users
  resources :roles

  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/logout',  to: 'sessions#destroy'

  #get    '/reserve'  to: 'reservation_write#new'
  #get    '/reserve'  to: 'reservations#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

bilardex_api/app/controllers/pool_tables_controller.rb
class PoolTablesController < ApplicationController
  before_action :set_pool_table, only: %i[ show edit update destroy ]

  # GET /pool_tables or /pool_tables.json
  def index
    @pool_tables = PoolTable.all
  end

  # GET /pool_tables/1 or /pool_tables/1.json
  def show
  end

  # GET /pool_tables/new
  def new
    @pool_table = PoolTable.new
  end

  # GET /pool_tables/1/edit
  def edit
  end

  # POST /pool_tables or /pool_tables.json
  def create
    @pool_table = PoolTable.new(pool_table_params)

    respond_to do |format|
      if @pool_table.save
        format.html { redirect_to pool_table_url(@pool_table), notice: "Pool table was successfully created." }
        format.json { render :show, status: :created, location: @pool_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pool_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pool_tables/1 or /pool_tables/1.json
  def update
    respond_to do |format|
      if @pool_table.update(pool_table_params)
        format.html { redirect_to pool_table_url(@pool_table), notice: "Pool table was successfully updated." }
        format.json { render :show, status: :ok, location: @pool_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pool_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pool_tables/1 or /pool_tables/1.json
  def destroy
    @pool_table.destroy

    respond_to do |format|
      format.html { redirect_to pool_tables_url, notice: "Pool table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool_table
      @pool_table = PoolTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pool_table_params
      params.require(:pool_table).permit(:position_x, :position_y, :table_type, :hourly_price)
    end
end

bilardex_api/app/helpers/pool_tables_helper.rb
module PoolTablesHelper
end

bilardex_api/app/views/pool_tables/_form.html.erb
<%= form_with(model: pool_table) do |form| %>
  <% if pool_table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pool_table.errors.count, "error") %> prohibited this pool_table from being saved:</h2>

      <ul>
        <% pool_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :position_x, style: "display: block" %>
    <%= form.text_field :position_x %>
  </div>

  <div>
    <%= form.label :position_y, style: "display: block" %>
    <%= form.text_field :position_y %>
  </div>

  <div>
    <%= form.label :table_type, style: "display: block" %>
    <%= form.text_field :table_type %>
  </div>

  <div>
    <%= form.label :hourly_price, style: "display: block" %>
    <%= form.text_field :hourly_price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

bilardex_api/app/views/pool_tables/_pool_table.html.erb
<div id="<%= dom_id pool_table %>">
  <p>
    <strong>Position x:</strong>
    <%= pool_table.position_x %>
  </p>

  <p>
    <strong>Position y:</strong>
    <%= pool_table.position_y %>
  </p>

  <p>
    <strong>Table type:</strong>
    <%= pool_table.table_type %>
  </p>

  <p>
    <strong>Hourly price:</strong>
    <%= pool_table.hourly_price %>
  </p>

</div>

bilardex_api/app/views/pool_tables/edit.html.erb
<h1>Editing pool table</h1>

<%= render "form", pool_table: @pool_table %>

<br>

<div>
  <%= link_to "Show this pool table", @pool_table %> |
  <%= link_to "Back to pool tables", pool_tables_path %>
</div>

bilardex_api/app/views/pool_tables/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pool tables</h1>

<div id="pool_tables">
  <% @pool_tables.each do |pool_table| %>
    <%= render pool_table %>
    <p>
      <%= link_to "Show this pool table", pool_table %>
    </p>
  <% end %>
</div>

<%= link_to "New pool table", new_pool_table_path %>

bilardex_api/app/views/pool_tables/new.html.erb
<h1>New pool table</h1>

<%= render "form", pool_table: @pool_table %>

<br>

<div>
  <%= link_to "Back to pool tables", pool_tables_path %>
</div>

bilardex_api/app/views/pool_tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pool_table %>

<div>
  <%= link_to "Edit this pool table", edit_pool_table_path(@pool_table) %> |
  <%= link_to "Back to pool tables", pool_tables_path %>

  <%= button_to "Destroy this pool table", @pool_table, method: :delete %>
</div>